# Composer file format version
version: "3"
services:
  server:
    # Path to build context
    build: ./backend
    # Name of the image
    image: weatherapp_backend
    # Service opens ports "host_port : container_port"
    ports:
     - "9000:9000"
    # Start command after image is build
    command: npm start
    # Volumes it uses
    volumes:
     - backend-vol:/backend
  frontend:
    image: weatherapp_frontend
    build: ./frontend
    # frontend depends on server, so it is build first
    depends_on:
     - server
    ports:
     - "8000:8000"
    command: npm start
    volumes:
     - frontend-vol:/frontend
volumes:
  frontend-vol:
  backend-vol: