version: '3'
services:
  server:
    image: weatherapp_backend
    ports:
     - "9000:9000"
    working_dir: /backend
    command: "npm start"
  webapp:
    image: weatherapp_backend
    working_dir: /frontend
    ports:
     - "8000:8000"
    command: "npm start"
     
volumes:
  server:
  webapp: